spring:
  application:
    name: service-client

  kafka:
    producer:
      # 发送端 系列化
      valueSerializer: com.gupaovip.service.client.kafka.ObjectSerializer
    consumer:
      group-id: gupao-group
      # consumer 反序列化
      valueDeserializer: com.gupaovip.service.client.kafka.ObjectDeserializer


  cloud:
    stream:
      bindings:
        person-source:
          destination: gupao
        person-sink:
          destination: gupao
          group: gupao-group
server:
  port: 9090 # 随机端口






