spring:
  application:
    name: service-provider

  cloud:
    gateway:
      routes:
        - id: rest
          uri: http://127.0.0.1:8056/hello # 被代理的 URI
          predicates:
            - Path=/rest/hello
          filters:
            - StripPrefix=1